Support full stash list with index on git-stash-list.

diff --git a/git-stash-list b/git-stash-list
--- a/git-stash-list
+++ b/git-stash-list
@@ -1,16 +1,16 @@
 #!/bin/bash
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]
 then
-    echo "git-stash-list v1.1"
-    echo "
-Lists each stash and its diff."
-    echo ""
-    echo "Usage:"
-    echo "    git stash-list"
-    echo ""
-    echo "    git stash-list --full"
-    echo ""
-    echo "    git stash-list INDEX"
+    echo "git-stash-list v1.2
+
+Lists each stash and its diff.
+
+Usage:
+
+    git stash-list [INDEX]
+
+    git stash-list --full [INDEX]
+"
     exit 0
 fi
 
@@ -22,8 +22,23 @@ then
     git show $(git stash list | cut -d":" -f 1)
 elif [ ! -z $1 ]
 then
-    echo $'\e[1;33m'"stash@{$1}"$'\e[0m'
-    git stash show "stash@{$1}"
+    if [ ! -z $2 ]
+    then
+        if [ "$1" == "--full" ]
+        then
+            git show "stash@{$2}"
+        else
+            echo "Sorry, I couldn't understand you. What did you say?"
+            sleep 1
+            echo ""
+            echo "Try,"
+            echo "  $ git stash-list 1"
+            exit 1
+        fi
+    else
+        echo $'\e[1;33m'"stash@{$1}"$'\e[0m'
+        git stash show "stash@{$1}"
+    fi
 else
     stashes=`git stash list`
     while read -r stash; do
